name: VitePress Deployment

on:
  push:
    branches:
      - vp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: vp

      - name: 🚧 Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: 🚀 Build VitePress application
        run: |
          yarn run build

      - name: 🎉 Commit and push changes to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
          commit_message: ${{ github.event.head_commit.message }}
          publish_branch: gh-pages
          publish_dir: ./dist
          cname: docs.sayu-bot.com
